-- Baseline schema — captured by introspection, not by `supabase db pull`.
--
-- This project was built without migrations: the schema below was created by
-- hand in the dashboard between May and August 2026. This file records that
-- pre-existing state so the database is reproducible from the repo.
--
-- IMPORTANT: this migration is NOT applied to the live project — everything in
-- it already exists there. It is the starting point for a fresh environment,
-- and the two migrations dated 2026-08-04 layer on top of it. Apply it only
-- when standing up a new project from scratch.

-- ─── donors ──────────────────────────────────────────────────────────────────
-- Names submitted through the Lightning donation card, shown on the supporter
-- ticker once approved.

create table if not exists public.donors (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name       text,
  approved   boolean default false
);

-- The original read policy. NOTE: RLS itself was not enabled until
-- 20260804120000_secure_donors_rls.sql, so this policy was inert until then —
-- see that migration for the full story.
create policy "Allow public read of approved donors"
  on public.donors for select to public
  using (approved = true);

-- ─── enqueue_donor_email ─────────────────────────────────────────────────────
-- Orphaned: public.donor_email_queue does not exist and no trigger references
-- this function. Recorded here because it was present in the live database when
-- this baseline was captured.
--
-- SUPERSEDED: dropped in 20260805063000_remove_orphaned_donor_email_worker.sql.
-- Kept here so the history stays honest — on a fresh apply it is created and
-- then removed, rather than the baseline being rewritten after the fact.

create or replace function public.enqueue_donor_email()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  insert into public.donor_email_queue(donor_id)
  values (new.id)
  on conflict (donor_id) do nothing;

  return new;
end;
$$;

-- ─── new_donor_notification ──────────────────────────────────────────────────
-- A Supabase Database Webhook: fires on every donor insert and POSTs the row to
-- a Make.com automation.
--
-- The real endpoint is deliberately NOT committed. A Make webhook URL is a
-- capability URL — anyone holding it can trigger the automation — and this
-- repository is public. Recreate it from the Supabase dashboard
-- (Database → Webhooks) rather than from this file, or substitute the URL below
-- from a secret store at apply time.
--
-- create trigger new_donor_notification
--   after insert on public.donors
--   for each row execute function supabase_functions.http_request(
--     '<MAKE_WEBHOOK_URL>',
--     'POST',
--     '{"Content-type":"application/json"}',
--     '{}',
--     '5000'
--   );
