-- Daily dashboard metrics, written by the GitHub Actions snapshot job.
-- Replaces a SQLite file on a home Proxmox box that the deployed app could
-- never read.
create table if not exists public.metric_snapshots (
  id          bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  -- Derived in UTC so the expression is IMMUTABLE and usable in an index.
  captured_on date generated always as ((captured_at at time zone 'UTC')::date) stored,
  metrics     jsonb not null
);

-- One row per day. Makes re-runs (including manual workflow_dispatch) idempotent
-- via upsert rather than accumulating duplicates.
create unique index if not exists metric_snapshots_captured_on_key
  on public.metric_snapshots (captured_on);

create index if not exists metric_snapshots_captured_at_idx
  on public.metric_snapshots (captured_at desc);

alter table public.metric_snapshots enable row level security;

-- Read-only to the public. Every value here is aggregate market data that is
-- already public at source, and the dashboard is expected to chart it. Writes
-- are service-role only: no insert/update/delete policy exists for anon.
create policy "public reads metric snapshots"
  on public.metric_snapshots for select to public
  using (true);
